namespace Get.RegexMachine;

partial class RegexCompiler<T>
{
    static DFAState ConvertToDFA(NFAState startState, RegexConflictBehavior conflictBehavior)
    {
        var unprocessedStates = new Queue<HashSet<NFAState>>();
        var processedStates = new Dictionary<HashSet<NFAState>, DFAState>(new HashSetEqualityComparer());
        var nextId = 0;

        // Start with the epsilon closure of the start state
        var initialState = EpsilonClosure([startState]);
        unprocessedStates.Enqueue(initialState);

        while (unprocessedStates.Count > 0)
        {
            var currentState = unprocessedStates.Dequeue();

            // Check if the state has already been processed
            if (!processedStates.TryGetValue(currentState, out var dfaState))
            {
                // Create a new DFA state
                processedStates[currentState] = dfaState = new DFAState(nextId++, GetValue(currentState, conflictBehavior));
            }

            // Collect all (range, target) pairs from all NFA states in the current set
            var rangeTargets = currentState
                .SelectMany(s => s.Transitions.Select(t => (t.Range, t.Targets)))
                .ToList();

            if (rangeTargets.Count == 0)
                continue;

            // Partition the character space at every range boundary
            // Collect all unique boundary points: each range's From and (To + 1)
            var boundaries = new SortedSet<char>();
            foreach (var (range, _) in rangeTargets)
            {
                boundaries.Add(range.From);
                if (range.To < char.MaxValue)
                    boundaries.Add((char)(range.To + 1));
            }

            // Build sub-ranges between consecutive boundaries
            char? prev = null;
            foreach (var b in boundaries)
            {
                if (prev.HasValue)
                {
                    var subRange = new CharRange(prev.Value, (char)(b - 1));
                    ProcessSubRange(subRange, rangeTargets, dfaState,
                        processedStates, unprocessedStates, conflictBehavior, ref nextId);
                }
                prev = b;
            }
            // Last sub-range from last boundary to char.MaxValue
            if (prev.HasValue)
            {
                var lastRange = new CharRange(prev.Value, char.MaxValue);
                ProcessSubRange(lastRange, rangeTargets, dfaState,
                    processedStates, unprocessedStates, conflictBehavior, ref nextId);
            }
        }

        return processedStates[initialState];
    }

    static void ProcessSubRange(
        CharRange subRange,
        List<(CharRange Range, HashSet<NFAState> Targets)> rangeTargets,
        DFAState dfaState,
        Dictionary<HashSet<NFAState>, DFAState> processedStates,
        Queue<HashSet<NFAState>> unprocessedStates,
        RegexConflictBehavior conflictBehavior,
        ref int nextId)
    {
        // Find which NFA states' ranges overlap this sub-range
        var nextNFAStates = new HashSet<NFAState>();
        foreach (var (range, targets) in rangeTargets)
        {
            if (range.Overlaps(subRange))
            {
                nextNFAStates.UnionWith(targets);
            }
        }

        if (nextNFAStates.Count == 0)
            return;

        var nextState = new HashSet<NFAState>(EpsilonClosure(nextNFAStates));
        if (!processedStates.TryGetValue(nextState, out var a))
        {
            unprocessedStates.Enqueue(nextState);
            processedStates[nextState] = a = new DFAState(nextId++, GetValue(nextState, conflictBehavior));
        }
        dfaState.AddTransition(subRange.From, subRange.To, a);
    }
    // Code Generated by Gemini
    static T? GetValue(HashSet<NFAState> states, RegexConflictBehavior conflictBehavior)
    {
        NFAState? maxState = null;
        int maxOrder = int.MinValue;

        int maxOrderCount = 0;
        foreach (var state in states)
        {
            if (state.IsAccepting)
            {
                if (state.Order > maxOrder)
                {
                    maxOrderCount = 1;
                    maxOrder = state.Order;
                    maxState = state;
                } else if (state.Order == maxOrder)
                {
                    maxOrderCount++;
                }
                // else: we are not considering that rule
            }
        }

        if (maxState == null)
        {
            return default;
        }

        if (conflictBehavior == RegexConflictBehavior.Last)
        {
            return maxState.Value;
        }
        if (maxOrderCount > 1)
        {
            var rules = states.Where(s => s.IsAccepting && s.Order == maxOrder).Select(s => s.Rule).Distinct();
            throw new RegexConflictCompilerException(rules.ToArray());
        }
        return maxState.Value;
    }
    // Code Generated by Gemini
    class HashSetEqualityComparer : IEqualityComparer<HashSet<NFAState>>
    {
        public bool Equals(HashSet<NFAState>? x, HashSet<NFAState>? y)
        {
            if (x == null || y == null)
            {
                return x == y;
            }

            return x.SetEquals(y);
        }

        public int GetHashCode(HashSet<NFAState> obj)
        {
            unchecked
            {
                int hash = obj.Count;
                foreach (var state in obj)
                {
                    hash ^= state.GetHashCode();
                }
                return hash;
            }
        }
    }
    // Code Generated by Gemini with some modifications
    // Helper function to calculate the epsilon closure of a set of NFA states
    static HashSet<NFAState> EpsilonClosure(IEnumerable<NFAState> states)
    {
        var closure = new HashSet<NFAState>(states);
        var worklist = new Queue<NFAState>(states);

        while (worklist.Count > 0)
        {
            var state = worklist.Dequeue();
            foreach (var epsilonState in state.Epsilon)
            {
                if (closure.Add(epsilonState))
                {
                    worklist.Enqueue(epsilonState);
                }
            }
        }

        return closure;
    }
    
    public class DFAState(int id, T? value)
    {
        /// <summary>
        /// Range-based transitions stored as sorted, non-overlapping (CharRange → DFAState) pairs.
        /// </summary>
        public List<(CharRange Range, DFAState State)> Transitions { get; } = [];

        /// <summary>Looks up the next state for a given character via range search.</summary>
        public DFAState? this[char c]
        {
            get
            {
                foreach (var (range, state) in Transitions)
                    if (range.Contains(c))
                        return state;
                return null;
            }
        }

        /// <summary>Convenience: walks a string through the DFA.</summary>
        public DFAState? this[string c]
        {
            get
            {
                if (c.Length is 0)
                    return null;
                var next = this[c[0]];
                if (next is null)
                    return null;
                if (c.Length == 1)
                    return next;
                else
                    return next[c[1..]];
            }
        }

        /// <summary>
        /// Adds a transition for the given character range, merging adjacent/overlapping ranges.
        /// </summary>
        public void AddTransition(char from, char to, DFAState target)
        {
            var newRange = new CharRange(from, to);
            for (int i = 0; i < Transitions.Count; i++)
            {
                var (range, state) = Transitions[i];
                if (state == target && range.CanMerge(newRange))
                {
                    // Merge with existing range for same target
                    Transitions[i] = (CharRange.Merge(range, newRange), state);
                    // Merge subsequent adjacent ranges for same target
                    while (i + 1 < Transitions.Count && Transitions[i + 1].State == target && Transitions[i].Range.CanMerge(Transitions[i + 1].Range))
                    {
                        Transitions[i] = (CharRange.Merge(Transitions[i].Range, Transitions[i + 1].Range), target);
                        Transitions.RemoveAt(i + 1);
                    }
                    return;
                }
                if (newRange.To < range.From)
                {
                    Transitions.Insert(i, (newRange, target));
                    return;
                }
            }
            Transitions.Add((newRange, target));
        }

        public int Id { get; } = id;
        public T? Value { get; internal set; } = value;
        public bool IsAccepting => Value != null;
        public override string ToString()
        {
            return $"{Id} ({Value as object ?? "null"}) => {{{string.Join(", ", Transitions.Select(t => t.Range.ToString()))}}}";
        }
    }
}
